import type { CRMRecord } from "./types";

// 79-row sample CRM export — "Routing Readiness Review" scenario
// Columns: record_id, account_name, domain, owner, segment, state, country, contact_name, email, phone
//
// Planted issues (matching dataset_summary.json):
//   • 14 missing owner fields   (blank / "TBD" / "Unknown")
//   • 12 duplicate account records (4 domain clusters × 3 records)
//   • 8 invalid email formats
//   • 51 inconsistent state values (full names, abbreviations, typos)
//   • 10 missing segment values (blank / "unknown")
//   • 9 naming format issues (ALL CAPS, leading/trailing spaces, mixed caps)

export const SAMPLE_DATA: CRMRecord[] = [
  // ── Rows 1–10 ────────────────────────────────────────────────────────────
  { record_id:"REC-001", account_name:"Northstar Health",          domain:"northstarhealth.com",     owner:"Noah Kim",         segment:"Enterprise",  state:"California",  country:"United States", contact_name:"Jordan Johnson",      email:"jordan.johnson@northstarhealth.com", phone:"(892) 858-9935" },
  { record_id:"REC-002", account_name:"ZENITH LABS",               domain:"zenithlabs.com",          owner:"Unknown",          segment:"Enterprise",  state:"California",  country:"United States", contact_name:"Logan Hall",          email:"logan@zenithlabs.com",              phone:"(438) 617-1434" },
  { record_id:"REC-003", account_name:"Altura Systems",            domain:"alturasystems.com",       owner:"Olivia Park",      segment:"Enterprise",  state:"IL",          country:"United States", contact_name:"Sam Flores",          email:"none@",                             phone:"(206) 877-3615" },
  { record_id:"REC-004", account_name:"Greenline Bio",             domain:"greenlinebio.com",        owner:"Ava Thompson",     segment:"Enterprise",  state:"WA",          country:"United States", contact_name:"Drew Johnson",        email:"drew.johnson@greenlinebio.com",     phone:"(294) 489-2584" },
  { record_id:"REC-005", account_name:"OrbitIQ",                   domain:"orbitiq.ai",              owner:"Sofia Martinez",   segment:"Enterprise",  state:"TX",          country:"United States", contact_name:"Skyler Ward",         email:"skyler.ward@orbitiq.ai",            phone:"(587) 180-5803" },
  { record_id:"REC-006", account_name:"CorePath",                  domain:"corepath.io",             owner:"Noah Kim",         segment:"SMB",         state:"Illinois",    country:"United States", contact_name:"Skyler Morris",       email:"skyler.morris@corepath.io",         phone:"(877) 333-5741" },
  { record_id:"REC-007", account_name:"SableWorks",                domain:"sableworks.com",          owner:"Olivia Park",      segment:"",            state:"CA",          country:"United States", contact_name:"Casey Patel",         email:"sam@",                              phone:"(366) 479-6820" },
  { record_id:"REC-008", account_name:"BluePeak Retail",           domain:"bluepeakretail.com",      owner:"Liam Carter",      segment:"unknown",     state:"tex.",        country:"United States", contact_name:"Jamie Wong",          email:"jamie@bluepeakretail.com",          phone:"(367) 573-7216" },
  { record_id:"REC-009", account_name:"SummitForge",               domain:"summitforge.com",         owner:"Ethan Brooks",     segment:"Enterprise",  state:"Texas",       country:"United States", contact_name:"Reese Martinez",      email:"reese.martinez@summitforge.com",    phone:"(523) 510-5386" },
  { record_id:"REC-010", account_name:"MeridianOps",               domain:"meridianops.com",         owner:"Ethan Brooks",     segment:"unknown",     state:"CA",          country:"United States", contact_name:"Sam Morris",          email:"smorris@meridianops.com",           phone:"(858) 569-3340" },
  // ── Rows 11–20 ───────────────────────────────────────────────────────────
  { record_id:"REC-011", account_name:"HarborCloud",               domain:"harborcloud.io",          owner:"Unknown",          segment:"SMB",         state:"TX",          country:"United States", contact_name:"Morgan Martinez",     email:"mmartinez@harborcloud.io",          phone:"(797) 508-6930" },
  { record_id:"REC-012", account_name:"LumenGrid",                 domain:"lumengrid.com",           owner:"Lucas Rivera",     segment:"Enterprise",  state:"New York",    country:"United States", contact_name:"Morgan Baker",        email:"morgan.baker@lumengrid.com",        phone:"(356) 742-3621" },
  { record_id:"REC-013", account_name:"Pinecrest Health",          domain:"pinecresthealth.com",     owner:"Olivia Park",      segment:"Mid-Market",  state:"ill.",        country:"United States", contact_name:"Harper Wong",         email:"harperwong@pinecresthealth.com",    phone:"(766) 981-1188" },
  { record_id:"REC-014", account_name:"EVERFIELD LOGISTICS",       domain:"everfieldlogistics.com",  owner:"Ethan Brooks",     segment:"Enterprise",  state:"CA",          country:"United States", contact_name:"Reese Johnson",       email:"rjohnson@everfieldlogistics.com",   phone:"(361) 564-1053" },
  { record_id:"REC-015", account_name:"AsterPoint",                domain:"asterpoint.com",          owner:"Isabella Nguyen",  segment:"Enterprise",  state:"TX",          country:"United States", contact_name:"Emerson Nguyen",      email:"emerson@asterpoint.com",            phone:"(356) 482-3646" },
  { record_id:"REC-016", account_name:"MapleStone Capital",        domain:"maplestonecap.com",       owner:"Liam Carter",      segment:"Mid-Market",  state:"IL",          country:"United States", contact_name:"Emerson Lee",         email:"emerson.lee@maplestonecap.com",     phone:"(314) 471-6038" },
  { record_id:"REC-017", account_name:"ClearSpring Media",         domain:"clearspringmedia.com",    owner:"Liam Carter",      segment:"Enterprise",  state:"New York",    country:"United States", contact_name:"Ava Martinez",        email:"hello@northstarhealth",             phone:"(270) 878-9727" },
  { record_id:"REC-018", account_name:"Verity Motors",             domain:"veritymotors.com",        owner:"Isabella Nguyen",  segment:"Enterprise",  state:"NY",          country:"United States", contact_name:"Morgan Allen",        email:"mallen@veritymotors.com",           phone:"(416) 652-4295" },
  { record_id:"REC-019", account_name:"Northwind Foods",           domain:"northwindfoods.com",      owner:"Lucas Rivera",     segment:"SMB",         state:"TX",          country:"United States", contact_name:"Cameron Turner",      email:"cameron.turner@northwindfoods.com", phone:"(453) 330-2049" },
  { record_id:"REC-020", account_name:"BrightArc Education",       domain:"brightarcedu.org",        owner:"Isabella Nguyen",  segment:"Enterprise",  state:"Texas",       country:"United States", contact_name:"Jordan Morris",       email:"jordan.morris@brightarcedu.org",    phone:"(272) 824-1964" },
  // ── Rows 21–30 ───────────────────────────────────────────────────────────
  { record_id:"REC-021", account_name:"Nimbus Telecom",            domain:"nimbustelecom.com",       owner:"Ethan Brooks",     segment:"unknown",     state:"n.y.",        country:"United States", contact_name:"Chris Smith",         email:"chris.wong#mail.com",               phone:"(885) 597-4510" },
  { record_id:"REC-022", account_name:"Cobalt Freight",            domain:"cobaltfreight.com",       owner:"Liam Carter",      segment:"Mid-Market",  state:"Illinois",    country:"United States", contact_name:"Morgan Morris",       email:"mmorris@cobaltfreight.com",         phone:"(616) 294-2545" },
  { record_id:"REC-023", account_name:"SilverOak Health",          domain:"silveroakhealth.com",     owner:"Olivia Park",      segment:"Mid-Market",  state:"CA",          country:"United States", contact_name:"Parker Turner",       email:"parker.turner@silveroakhealth.com", phone:"(889) 769-2612" },
  { record_id:"REC-024", account_name:"IronBridge Systems",        domain:"ironbridgesys.com",       owner:"Jordan Patel",     segment:"Enterprise",  state:"California",  country:"United States", contact_name:"cameron   LOPEZ",     email:"cameron@ironbridgesys.com",         phone:"(749) 559-3296" },
  { record_id:"REC-025", account_name:"NovaVista Energy",          domain:"novavistaenergy.com",     owner:"TBD",              segment:"Enterprise",  state:"Washington",  country:"United States", contact_name:"Riley Johnson",       email:"rjohnson@novavistaenergy.com",      phone:"(763) 200-1828" },
  { record_id:"REC-026", account_name:"Atlas Commerce",            domain:"atlascommerce.com",       owner:"Noah Kim",         segment:"Enterprise",  state:"IL",          country:"United States", contact_name:"Jordan Wong",         email:"jwong@atlascommerce.com",           phone:"(692) 318-7570" },
  { record_id:"REC-027", account_name:"HelioWave",                 domain:"heliowave.com",           owner:"Maya Chen",        segment:"Mid-Market",  state:"CA",          country:"United States", contact_name:"Riley Clark",         email:"rclark@heliowave.com",              phone:"(492) 533-8973" },
  { record_id:"REC-028", account_name:"Redwood Biologics",         domain:"redwoodbio.com",          owner:"Noah Kim",         segment:"Enterprise",  state:"New York",    country:"United States", contact_name:"Sam Davis",           email:"samdavis@redwoodbio.com",           phone:"(258) 151-8811" },
  { record_id:"REC-029", account_name:"VectorLane",                domain:"vectorlane.io",           owner:"Maya Chen",        segment:"SMB",         state:"Illinois",    country:"United States", contact_name:"Emerson Nguyen",      email:"riley.com",                         phone:"(270) 709-2113" },
  { record_id:"REC-030", account_name:"TruNorth Security",         domain:"trunorthsec.com",         owner:"Liam Carter",      segment:"Enterprise",  state:"n.y.",        country:"United States", contact_name:"Cameron Patel",       email:"cameron.patel@trunorthsec.com",     phone:"(629) 773-9565" },
  // ── Rows 31–40 ───────────────────────────────────────────────────────────
  { record_id:"REC-031", account_name:"Golden Harbor Travel",      domain:"goldenharbortravel.com",  owner:"",                 segment:"Enterprise",  state:"TX",          country:"United States", contact_name:"Jamie Brooks",        email:"jbrooks@goldenharbortravel.com",    phone:"(334) 787-5915" },
  { record_id:"REC-032", account_name:"CloudMosaic",               domain:"cloudmosaic.io",          owner:"Maya Chen",        segment:"Mid-Market",  state:"ill.",        country:"United States", contact_name:"Drew Wong",           email:"drew.wong@cloudmosaic.io",          phone:"(750) 318-9288" },
  { record_id:"REC-033", account_name:"PeakRiver Finance",         domain:"peakriverfin.com",        owner:"Jordan Patel",     segment:"Enterprise",  state:"Tex",         country:"United States", contact_name:"Morgan Turner",       email:"morganturner@peakriverfin.com",     phone:"(361) 548-9900" },
  { record_id:"REC-034", account_name:"Bridgewell Care",           domain:"bridgewellcare.com",      owner:"",                 segment:"SMB",         state:"TX",          country:"United States", contact_name:"Harper Baker",        email:"harper.baker@bridgewellcare.com",   phone:"(337) 370-2891" },
  { record_id:"REC-035", account_name:"Stratus One",               domain:"stratusone.com",          owner:"Sofia Martinez",   segment:"Mid-Market",  state:"tex.",        country:"United States", contact_name:"Reese Kim",           email:"reesekim@stratusone.com",           phone:"(408) 803-5325" },
  { record_id:"REC-036", account_name:"Beacon Supply",             domain:"beaconsupplyco.com",      owner:"Unknown",          segment:"Enterprise",  state:"IL",          country:"United States", contact_name:"Rowan Johnson",       email:"rowanjohnson@beaconsupplyco.com",   phone:"(245) 103-6464" },
  { record_id:"REC-037", account_name:"WESTGATE HEALTH",           domain:"westgatehealth.com",      owner:"Lucas Rivera",     segment:"SMB",         state:"NY",          country:"United States", contact_name:"Jamie Nguyen",        email:"jamie.nguyen@westgatehealth.com",   phone:"(314) 177-3442" },
  { record_id:"REC-038", account_name:"UrbanNest Living",          domain:"urbannestliving.com",     owner:"Liam Carter",      segment:"unknown",     state:"Illinois",    country:"United States", contact_name:"Ava Turner",          email:"aturner@urbannestliving.com",       phone:"(330) 142-6050" },
  { record_id:"REC-039", account_name:"Tidal Metrics",             domain:"tidalmetrics.io",         owner:"Noah Kim",         segment:"SMB",         state:"Texas",       country:"United States", contact_name:"Ava Turner",          email:"ava.turner@tidalmetrics.io",        phone:"(562) 898-7658" },
  { record_id:"REC-040", account_name:"FieldStone Manufacturing",  domain:"fieldstonemfg.com",       owner:"Ava Thompson",     segment:"Enterprise",  state:"n.y.",        country:"United States", contact_name:"Morgan Martinez",     email:"morgan.martinez@fieldstonemfg.com", phone:"(383) 854-6442" },
  // ── Rows 41–50 ───────────────────────────────────────────────────────────
  { record_id:"REC-041", account_name:"ArcBloom",                  domain:"arcbloom.com",            owner:"Ava Thompson",     segment:"SMB",         state:"Washington",  country:"United States", contact_name:"Casey Johnson",       email:"cjohnson@arcbloom.com",             phone:"(239) 979-8711" },
  { record_id:"REC-042", account_name:"Praxis Medical",            domain:"praxismedical.com",       owner:"Ethan Brooks",     segment:"",            state:"New York",    country:"United States", contact_name:"Sam Young",           email:"sam@praxismedical.com",             phone:"(224) 775-4164" },
  { record_id:"REC-043", account_name:"Voltaris",                  domain:"voltaris.com",            owner:"Jordan Patel",     segment:"Mid-Market",  state:"tex.",        country:"United States", contact_name:"Drew Johnson",        email:"djohnson@voltaris.com",             phone:"(895) 963-9785" },
  { record_id:"REC-044", account_name:"Oakline Systems",           domain:"oaklinesystems.com",      owner:"TBD",              segment:"Enterprise",  state:"TX",          country:"United States", contact_name:"jordan   PATEL",      email:"jordan.patel@oaklinesystems.com",   phone:"(311) 710-8119" },
  { record_id:"REC-045", account_name:"Crescent Foods",            domain:"crescentfoods.com",       owner:"Liam Carter",      segment:"SMB",         state:"ill.",        country:"United States", contact_name:"Drew Hall",           email:"dhall@crescentfoods.com",           phone:"(790) 294-5173" },
  { record_id:"REC-046", account_name:"TrueSpan Networks",         domain:"truespan.net",            owner:"Isabella Nguyen",  segment:"SMB",         state:"Cal",         country:"United States", contact_name:"Parker Lee",          email:"parkerlee@truespan.net",            phone:"(641) 171-6409" },
  { record_id:"REC-047", account_name:"MiraPath",                  domain:"mirapath.com",            owner:"Sofia Martinez",   segment:"SMB",         state:"calif.",      country:"United States", contact_name:"Drew Patel",          email:"dpatel@mirapath.com",               phone:"(534) 512-5844" },
  { record_id:"REC-048", account_name:"SkyLedger",                 domain:"skyledger.io",            owner:"Olivia Park",      segment:"",            state:"New york",    country:"United States", contact_name:"Morgan Brooks",       email:"morgan@skyledger.io",               phone:"(830) 682-5930" },
  { record_id:"REC-049", account_name:"NorthGrove",                domain:"northgrove.com",          owner:"Sofia Martinez",   segment:"Mid-Market",  state:"Washington",  country:"United States", contact_name:"Reese Lee",           email:"rlee@northgrove.com",               phone:"(793) 721-6279" },
  { record_id:"REC-050", account_name:"TerraFleet",                domain:"terrafleet.com",          owner:"Noah Kim",         segment:"SMB",         state:"WA",          country:"United States", contact_name:"Quinn Young",         email:"quinn@terrafleet.com",              phone:"(874) 186-5649" },
  // ── Rows 51–60 ───────────────────────────────────────────────────────────
  { record_id:"REC-051", account_name:"Aquila Health",             domain:"aquilahealth.com",        owner:"Jordan Patel",     segment:"Enterprise",  state:"IL",          country:"United States", contact_name:"Harper Lopez",        email:"harper@aquilahealth.com",           phone:"(403) 250-1400" },
  { record_id:"REC-052", account_name:"PrimeLayer",                domain:"primelayer.io",           owner:"Liam Carter",      segment:"",            state:"CA",          country:"United States", contact_name:"Casey Allen",         email:"callen@primelayer.io",              phone:"(844) 689-4185" },
  { record_id:"REC-053", account_name:"SummitRail",                domain:"summitrail.com",          owner:"TBD",              segment:"Enterprise",  state:"Washington",  country:"United States", contact_name:"Rowan Clark",         email:"rowan.clark@summitrail.com",        phone:"(997) 535-4585" },
  { record_id:"REC-054", account_name:"BlueRidge Labs",            domain:"blueridgelabs.com",       owner:"Maya Chen",        segment:"SMB",         state:"New York",    country:"United States", contact_name:"Emerson Young",       email:"emerson.young@blueridgelabs.com",   phone:"(667) 236-8612" },
  { record_id:"REC-055", account_name:"CivicAxis",                 domain:"civicaxis.org",           owner:"Ethan Brooks",     segment:"Mid-Market",  state:"Ill",         country:"United States", contact_name:"Reese Ward",          email:"rward@civicaxis.org",               phone:"(362) 861-8777" },
  { record_id:"REC-056", account_name:"Element Harbor",            domain:"elementharbor.com",       owner:"Sofia Martinez",   segment:"SMB",         state:"WA",          country:"United States", contact_name:"Jamie Martinez",      email:"jamie@elementharbor.com",           phone:"(481) 550-2269" },
  { record_id:"REC-057", account_name:"  vantacore  ",             domain:"vantacore.com",           owner:"Ethan Brooks",     segment:"",            state:"Texas",       country:"United States", contact_name:"Casey Johnson",       email:"casey@vantacore.com",               phone:"(354) 336-7275" },
  { record_id:"REC-058", account_name:"BrightField",               domain:"brightfieldag.com",       owner:"Olivia Park",      segment:"Mid-Market",  state:"NY",          country:"United States", contact_name:"Sam Wong",            email:"swong@brightfieldag.com",           phone:"(625) 163-4388" },
  { record_id:"REC-059", account_name:"OpenTrail",                 domain:"opentrail.io",            owner:"Maya Chen",        segment:"SMB",         state:"New york",    country:"United States", contact_name:"Cameron Morris",      email:"test",                              phone:"(206) 460-5892" },
  { record_id:"REC-060", account_name:"SignalForge",               domain:"signalforge.com",         owner:"Isabella Nguyen",  segment:"SMB",         state:"Washington",  country:"United States", contact_name:"Parker Flores",       email:"pflores@signalforge.com",           phone:"(424) 379-8140" },
  // ── Rows 61–70 ───────────────────────────────────────────────────────────
  { record_id:"REC-061", account_name:"  granitecare  ",           domain:"granitecare.com",         owner:"TBD",              segment:"SMB",         state:"Wash",        country:"United States", contact_name:"Jordan Clark",        email:"jordan@granitecare.com",            phone:"(678) 230-9751" },
  { record_id:"REC-062", account_name:"  echovista  ",             domain:"echovista.co",            owner:"Liam Carter",      segment:"SMB",         state:"California",  country:"United States", contact_name:"Cameron Morris",      email:"cameron.morris@echovista.co",       phone:"(858) 538-3223" },
  { record_id:"REC-063", account_name:"DeltaBridge",               domain:"deltabridge.com",         owner:"Unknown",          segment:"Mid-Market",  state:"tex.",        country:"United States", contact_name:"Riley Smith",         email:"riley@deltabridge.com",             phone:"(665) 434-6529" },
  { record_id:"REC-064", account_name:"RiverMint",                 domain:"rivermint.com",           owner:"Sofia Martinez",   segment:"Enterprise",  state:"WA",          country:"United States", contact_name:"Jamie Hall",          email:"jamie.hall@rivermint.com",          phone:"(967) 652-1853" },
  { record_id:"REC-065", account_name:"PureLine Labs",             domain:"purelinelabs.com",        owner:"Maya Chen",        segment:"Enterprise",  state:"Texas",       country:"United States", contact_name:"Casey Wong",          email:"casey@purelinelabs.com",            phone:"(220) 736-3496" },
  { record_id:"REC-066", account_name:"North Harbor Tech",         domain:"northharbortech.com",     owner:"Jordan Patel",     segment:"unknown",     state:"New York",    country:"United States", contact_name:"Morgan Allen",        email:"mallen@northharbortech.com",        phone:"(916) 362-7043" },
  { record_id:"REC-067", account_name:"VerdeLink",                 domain:"verdelink.com",           owner:"",                 segment:"Enterprise",  state:"NY",          country:"United States", contact_name:"Harper Ward",         email:"harper.ward@verdelink.com",         phone:"(792) 126-6111" },
  // ── Duplicate cluster 1: northstarhealth.com ──────────────────────────────
  { record_id:"REC-068", account_name:"Northstar Health LLC",      domain:"northstarhealth.com",     owner:"Noah Kim",         segment:"Enterprise",  state:"Ill",         country:"United States", contact_name:"Cameron Brooks",      email:"cameron.brooks@northstarhealth.com",phone:"(892) 858-9935" },
  { record_id:"REC-069", account_name:"NORTHSTAR HEALTH",          domain:"northstarhealth.com",     owner:"Noah Kim",         segment:"Enterprise",  state:"California",  country:"United States", contact_name:"Taylor Davis",        email:"ava@acme",                          phone:"(892) 858-9935" },
  // ── Duplicate cluster 2: sableworks.com ───────────────────────────────────
  { record_id:"REC-070", account_name:"SableWorks Inc",            domain:"sableworks.com",          owner:"",                 segment:"Mid-Market",  state:"CA",          country:"United States", contact_name:"Skyler Flores",       email:"sflores@sableworks.com",            phone:"(366) 479-6820" },
  { record_id:"REC-071", account_name:"SableWorks, Inc.",          domain:"sableworks.com",          owner:"Olivia Park",      segment:"Mid-Market",  state:"tex.",        country:"United States", contact_name:"Chris Baker",         email:"chrisbaker@sableworks.com",         phone:"(366) 479-6820" },
  // ── Duplicate cluster 3: lumengrid.com ────────────────────────────────────
  { record_id:"REC-072", account_name:"LumenGrid Inc",             domain:"lumengrid.com",           owner:"TBD",              segment:"Enterprise",  state:"New York",    country:"United States", contact_name:"Parker Allen",        email:"parker.allen@lumengrid.com",        phone:"(356) 742-3621" },
  { record_id:"REC-073", account_name:"LumenGrid LLC",             domain:"lumengrid.com",           owner:"Lucas Rivera",     segment:"Enterprise",  state:"New York",    country:"United States", contact_name:"Skyler Young",        email:"skyler@lumengrid.com",              phone:"(356) 742-3621" },
  // ── Duplicate cluster 4: northwindfoods.com ───────────────────────────────
  { record_id:"REC-074", account_name:"NORTHWIND FOODS LLC",       domain:"northwindfoods.com",      owner:"Lucas Rivera",     segment:"SMB",         state:"TX",          country:"United States", contact_name:"Riley Baker",         email:"rileybaker@northwindfoods.com",     phone:"(453) 330-2049" },
  { record_id:"REC-075", account_name:"Northwind Foods LLC",       domain:"northwindfoods.com",      owner:"Lucas Rivera",     segment:"SMB",         state:"New york",    country:"United States", contact_name:"Quinn Hall",          email:"quinnhall@northwindfoods.com",      phone:"(453) 330-2049" },
  // ── Duplicate cluster 5: redwoodbio.com ───────────────────────────────────
  { record_id:"REC-076", account_name:"Redwood Biologics, Inc.",   domain:"redwoodbio.com",          owner:"Noah Kim",         segment:"Enterprise",  state:"New York",    country:"United States", contact_name:"Casey Wong",          email:"jordan.leecompany.com",             phone:"(258) 151-8811" },
  { record_id:"REC-077", account_name:"Redwood Biologics LLC",     domain:"redwoodbio.com",          owner:"",                 segment:"Enterprise",  state:"New York",    country:"United States", contact_name:"Casey Young",         email:"cyoung@redwoodbio.com",             phone:"(258) 151-8811" },
  // ── Duplicate cluster 6: stratusone.com ───────────────────────────────────
  { record_id:"REC-078", account_name:"Stratus One, Inc.",         domain:"stratusone.com",          owner:"Sofia Martinez",   segment:"Mid-Market",  state:"New york",    country:"United States", contact_name:"Jordan Allen",        email:"jordanallen@stratusone.com",        phone:"(408) 803-5325" },
  { record_id:"REC-079", account_name:"STRATUS ONE",               domain:"stratusone.com",          owner:"Sofia Martinez",   segment:"Mid-Market",  state:"California",  country:"United States", contact_name:"Rowan Brooks",        email:"rowanbrooks@stratusone.com",        phone:"(408) 803-5325" },
];

export const DATASET_META = {
  fileName: "messy_crm_export.csv",
  rowCount: 79,
  columnCount: 10,
  uploadedAt: "2026-04-20T09:14:32Z",
  columns: [
    { key: "record_id",    label: "Record ID",    detected: true },
    { key: "account_name", label: "Account Name", detected: true },
    { key: "domain",       label: "Domain",       detected: true },
    { key: "owner",        label: "Owner",        detected: true },
    { key: "segment",      label: "Segment",      detected: true },
    { key: "state",        label: "State",        detected: true },
    { key: "country",      label: "Country",      detected: true },
    { key: "contact_name", label: "Contact Name", detected: true },
    { key: "email",        label: "Email",        detected: true },
    { key: "phone",        label: "Phone",        detected: true },
  ],
};
